env:
  - NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE grassinvaders;" -U postgres
  - psql -c "CREATE USER grassinvaders WITH PASSWORD ''"; -U postgres
  - psql -U grassinvaders -d grassinvaders -f ../database/schema.sql
language: node_js
node_js:
  - 10