version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB="grassinvaders"
      - POSTGRES_USER="grassinvaders"
      - POSTGRES_PASSWORD="password"
  api:
    image: martinmhan/grass-invaders-prod
    depends_on:
      - db
    ports:
      - "3000:3000"